version: "3"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssqlserver         # container name
    restart: always
    hostname: mssql
    environment:
      SA_PASSWORD: password123          # password
      ACCEPT_EULA: Y

    ports:
      - "1433:1433"                     # port